name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Build
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pylint
        pip list
    - name: Use pylint
      run: |
        source .env/bin/activate
        find . -maxdepth 2 -type f -name "*.py" | xargs pylint --exit-zero
    - name: Testing
      run: |
        source .env/bin/activate
        pytest flaskr/tests.py
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-testing
    steps:
    - name: deploy staging
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME}}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
        script: |
          cd ${{ secrets.DEV}}
          git pull origin main
          source .env/bin/activate
          pip install -r requirements.txt
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
    - name: deploy prod
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME}}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
        script: |
          cd ${{ secrets.PROD }}
          git pull origin main
          source .env/bin/activate
          pip install -r requirements.txt
